### ISSUE TITLE
Update .gitignore to ignore .mat files

### ISSUE THREAD

**Issue by XinhuiLi** [trendscenter/MISA-pytorch#6]
- [x] Update .gitignore to ignore .mat files
- [x] Remove unnecessary files in simulation_data folder

**Comment by rsilva8** [comment]
Let's keep the simulation_data folder.
Mat files are saved in there but not pushed to repository.

**Comment by rsilva8** [comment]
Make sure the files are readable by everyone so we can make copy into our local/personal folders
